name: FurstaSeq
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - comm=0.2.3
  - debugpy=1.8.11
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.1
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=9.4.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - krb5=1.21.3
  - libcxx=17.0.6
  - libedit=3.1.20250104
  - libffi=3.4.4
  - libsodium=1.0.20
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.5.1
  - packaging=25.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.1
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.12.11
  - python-dateutil=2.9.0.post0
  - pyzmq=26.2.0
  - readline=8.2
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tk=8.6.14
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.14.1
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.2.13
  - pip:
      - absl-py==2.3.1
      - accelerate==1.9.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - alembic==1.16.4
      - anndata==0.12.2
      - annotated-types==0.7.0
      - appdirs==1.4.4
      - array-api-compat==1.12.0
      - attrs==25.3.0
      - biom-format==2.1.17
      - biopython==1.85
      - biotrainer==1.0.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.2
      - click==8.3.0
      - colorlog==6.9.0
      - contourpy==1.3.3
      - crc32c==2.7.1
      - cycler==0.12.1
      - cyclopts==3.22.5
      - datasets==4.0.0
      - dill==0.3.8
      - docstring-parser==0.17.0
      - docutils==0.22
      - donfig==0.8.1.post1
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - fire==0.7.0
      - fonttools==4.59.0
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.74.0
      - h5py==3.14.0
      - hf-xet==1.1.5
      - huggingface-hub==0.34.3
      - idna==3.10
      - jinja2==3.1.6
      - joblib==1.5.1
      - jsonschema==4.25.0
      - jsonschema-specifications==2025.4.1
      - kiwisolver==1.4.9
      - legacy-api-wrap==1.4.1
      - lightning==2.5.5
      - lightning-utilities==0.15.1
      - llvmlite==0.44.0
      - mako==1.3.10
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.5
      - mdurl==0.1.2
      - ml-dtypes==0.5.3
      - mpmath==1.3.0
      - multidict==6.6.3
      - multiprocess==0.70.16
      - narwhals==2.1.1
      - natsort==8.4.0
      - nbformat==5.10.4
      - networkx==3.5
      - numba==0.61.2
      - numcodecs==0.16.3
      - numpy==2.2.5
      - onnx==1.16.1
      - onnx-ir==0.1.4
      - onnxscript==0.3.2
      - optuna==4.4.0
      - optuna-integration==4.6.0
      - pandas==2.3.1
      - patsy==1.0.1
      - peft==0.17.0
      - pillow==11.3.0
      - plotly==6.3.0
      - propcache==0.3.2
      - protobuf==6.31.1
      - psutil==7.0.0
      - pyarrow==21.0.0
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pynndescent==0.5.13
      - pyparsing==3.2.3
      - pytorch-lightning==2.5.5
      - pytz==2025.2
      - pyyaml==6.0.2
      - randomname==0.2.1
      - referencing==0.36.2
      - regex==2025.7.34
      - requests==2.32.4
      - rich==14.1.0
      - rich-rst==1.3.1
      - rpds-py==0.27.0
      - ruamel-yaml==0.17.40
      - ruamel-yaml-clib==0.2.12
      - safetensors==0.5.3
      - scanpy==1.11.4
      - scikit-bio==0.7.0
      - scikit-learn==1.7.1
      - scipy==1.15.2
      - seaborn==0.13.2
      - sentencepiece==0.2.0
      - sentry-sdk==2.42.1
      - session-info2==0.2.2
      - smmap==5.0.2
      - sqlalchemy==2.0.42
      - statsmodels==0.14.5
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tokenizers==0.21.4
      - torch==2.7.1
      - torchaudio==2.7.1
      - torchmetrics==1.8.0
      - torchvision==0.22.1
      - tqdm==4.67.1
      - transformers==4.54.1
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - umap-learn==0.5.9.post2
      - urllib3==2.5.0
      - wandb==0.22.2
      - werkzeug==3.1.3
      - xxhash==3.5.0
      - yarl==1.20.1
      - zarr==3.1.3
